name: clone-jadi.net

on: 
  push: 
    branches:
      - master
jobs:
  cloning:
    runs-on: ubuntu-latest

    steps:
      - name: Installing httrack
        run: |
          sudo apt-get update
          sudo apt-get install -y wget

      - name: create new dir
        run: mkdir docs

      - name: Clone using httrack
        run: |
          wget --mirror --convert-links --adjust-extension --page-requisites --no-parent https://jadi.net/ -P ./docs

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add docs
          git commit -m "Update website content from jadi.net [${{ github.event.time }}]"
          git push origin HEAD:main

